# Log Forwarding Profile vars
log_forward_profile: 'default'

# Log Forwarding Profile Match List vars
# log_type must be one of: traffic, threat, wildfire, url, data, gtp, tunnel, auth, sctp. 
log_type: 'traffic'
syslog_server_profile_name: 'Main_SYSLOG_Profile'

